Init Window Prototype
thehighestmath/sea_battle pull request #1
Opened 2021-03-13 14:11 UTC by Anya18

2021-03-13 17:59 UTC, thehighestmath commented on InitWindow.py
> +        InitWindow.setStyleSheet("#InitWindow {\n"
Разве сюда многострочная строка не пойдет?
Типа
```"""Ааа
Ааа
Ббб"""```
?

2021-03-13 18:00 UTC, thehighestmath commented on InitWindow.py
> +        self.label.setStyleSheet("#label {\n"
Тот же вопрос

2021-03-13 18:01 UTC, thehighestmath reviewed
Аня молодец!

2021-03-13 18:30 UTC, thehighestmath approved these changes

2021-03-27 08:17 UTC, kinekt2000 requested changes
Необходимы (не уверен) мелкие быстрофиксы.

2021-03-27 08:17 UTC, kinekt2000 commented on main.py
> +class InitWindow(QtWidgets.QMainWindow, InitWindow.Ui_InitWindow):
Преобразуй класс в виджет (Наследуйся от QWidget), чтоб его можно было свопать из главного окна с помощью различных событий будь то нажатия твоих кнопок, кнопок менюбара или смена состояния игры.

```suggestion
class InitWindow(QtWidgets.QWidget, InitWindow.Ui_InitWindow):
```

2021-03-27 08:17 UTC, kinekt2000 commented on main.py
> +        print("showHST")
Может быть в будущем пригодится проброс сигналов в главное окно.

2021-03-27 08:17 UTC, kinekt2000 commented on InitWindow.py
> +        InitWindow.setFixedSize(400, 500)
Не думаю, что тебе необходимо устанавливать Fixed. Попробуй сделать динамически расширяемый виджет.

2021-03-27 10:35 UTC, kinekt2000 commented
И забрось весь код в директорию src пж :)

2021-04-07 09:18 UTC, kinekt2000 requested changes
Добавь в директорию OffGame пустой файл __init__.py

2021-04-07 09:18 UTC, kinekt2000 commented on src/OffGame/InitWidget.py
> +from UI_InitWidget import Ui_InitWidget
Импортируй из модуля
```suggestion
from OffGame.UI_InitWidget import Ui_InitWidget
```

2021-04-07 09:19 UTC, thehighestmath commented
__init__.py
@kinekt2000

2021-04-07 09:20 UTC, thehighestmath commented
Markdown работает когда не нужно

2021-04-07 09:46 UTC, kinekt2000 approved these changes

2021-04-07 10:09 UTC, merged