Game window
thehighestmath/sea_battle pull request #14
Opened 2021-03-27 19:28 UTC by thehighestmath

Чтобы это работало нужно 
- чтобы был фон, картинка ship.jpg в папке src.
- чтобы Костин код был в src/view
- чтобы Костины ресурсы были в src/view/res

![image](https://user-images.githubusercontent.com/42893255/112732546-acd6a780-8f4b-11eb-878a-01bca73db6a2.png)
Пока такая структура, ну а что поделать(

2021-03-27 20:46 UTC, kinekt2000 requested changes
В остальном все четко :)

2021-03-27 20:46 UTC, kinekt2000 commented on src/GameWindow.py
> +class GameWindow(QtWidgets.QMainWindow):
Переделать в QWidget!

```suggestion
class GameWindow(QtWidgets.QWidget):
```

2021-03-27 20:46 UTC, kinekt2000 commented on src/GameWindow.py
> +        self.ui.wigdet_player_2.setGraphicsEffect(None)
Преобразовать в стейт-машину с использованием одного слота (метода).
Не обязательно к выполнению, но рекомендую

2021-03-27 20:46 UTC, kinekt2000 commented on src/GameWindow.py
> +        super(GameWindow, self).mousePressEvent(event)
На деле необходимости перехватывать события мыши нет. Пометь, что обработчик для дебага, либо убери его.

2021-03-27 20:46 UTC, kinekt2000 commented on src/gamewindow_ui.py
> +        GameWindow.setMaximumSize(QtCore.QSize(1000, 600))
Твой виджет не является основным, лучше сделать его способным динамически менять размер

2021-03-27 22:04 UTC, thehighestmath commented on src/GameWindow.py
> +        super(GameWindow, self).mousePressEvent(event)
А вдруг потом понадобится! И он уже будет ;)

2021-03-27 22:04 UTC, thehighestmath commented on src/gamewindow_ui.py
> +        GameWindow.setMaximumSize(QtCore.QSize(1000, 600))
Ну лан, ты прав

2021-03-27 22:05 UTC, thehighestmath commented on src/GameWindow.py
> +class GameWindow(QtWidgets.QMainWindow):
:(
Ну лан((

2021-03-27 22:09 UTC, thehighestmath commented on src/GameWindow.py
> +        self.ui.wigdet_player_2.setGraphicsEffect(None)
Обернуть в 1 метод можно, а ещё можно сделать методы в методе
Но даже если не делать такой вложенности то как наше метод, условно `state_machine()` будет понимать в какое состояние переходить? Окей `state_machine(type)` в зависимости от `type` но тогда метод будет огромный? Или просто обертку над этими 4-мя методами сделать? Типа
```
def prepare_player_1(self):
    pass
def prepare_player_2(self):
    pass
def player_1(self):
    pass
def player_2(self):
    pass
def state_machine(type):
    if type == 1:
        prepare_player_1()
    if type == 2:
        prepare_player_2()
    if type == 3:
        player_1()
    if type == 4:
        player_2()
```
Типа такого сделать?

2021-03-28 12:00 UTC, kinekt2000 commented on src/GameWindow.py
> +            raise Exception(f'Unknown type: {type_}')
Теперь по вызову Next() твой класс способен сам понимать, что и какому игроку надо обеспечить. Только нужно заранее сохранить то, какой игрок сейчас что-то делает.

```suggestion
    def Next(self):
        if self.currentState == States.UNDEFINED:
            self.currentPlayer = random.randint(1, 2)
            self.currentState = States.FIRST_PREPARE
            self.PreparePlayer(self.currentPlayer)

        elif self.currentState == States.FIRST_PREPARE:
            self.currentPlayer = 2 if self.currentPlayer == 1 else 1
            self.currentState = States.SECOND_PREPARE
            self.PreparePlayer(self.currentPlayer)

        elif self.currentState == States.SECOND_PREPARE:
            self.currentPlayer = random.randint(1, 2)
            self.currentState = States.GAME
            self.MovePlayer(self.currentPlayer)

        elif self.currentState == States.GAME:
            self.currentPlayer = 2 if self.currentPlayer == 1 else 1
            self.MovePlayer(self.currentPlayer)
```

2021-03-28 12:00 UTC, kinekt2000 commented on src/GameWindow.py
> +        self.ui.wigdet_player_2.setGraphicsEffect(None)
Типа такого, но иначе. В чем смысл стейт-машины, Если ты сам устанавливаешь состояние.

2021-03-28 12:01 UTC, kinekt2000 requested changes
Вроде как остальное пускай остается, выглядит прилично

2021-03-28 12:11 UTC, thehighestmath commented on src/GameWindow.py
> +            raise Exception(f'Unknown type: {type_}')
Ну я первый раз с ней работаю

_Уф, нейминг методов, зубы скрепят..._

2021-03-28 12:31 UTC, thehighestmath commented on src/GameWindow.py
> +            raise Exception(f'Unknown type: {type_}')
Такс, а если я попал в корабль? Я не хочу ход отдавать(

2021-03-28 15:56 UTC, kinekt2000 commented on src/GameWindow.py
> +            raise Exception(f'Unknown type: {type_}')
А, внатуре, ну тогда аргумент методу задай, типа keep_player

2021-03-28 16:40 UTC, thehighestmath commented on src/GameWindow.py
> +            raise Exception(f'Unknown type: {type_}')
Вот вот(

Надо подумать

2021-03-28 16:42 UTC, thehighestmath commented on src/GameWindow.py
> +            raise Exception(f'Unknown type: {type_}')
`def next(self, keep_player: bool = False)` Типа такого?

2021-03-28 16:48 UTC, kinekt2000 commented on src/GameWindow.py
> +            raise Exception(f'Unknown type: {type_}')
Да

2021-03-28 18:03 UTC, thehighestmath commented
Давай, души!

2021-03-28 21:10 UTC, thehighestmath commented
Хоткеи
Q -- это простая передача хода
W -- передача хода с сохранением игрока (попал в корабль)

Меню в меню-баре, возможно, стоит убрать

2021-03-29 10:21 UTC, kinekt2000 requested changes
Подозреваю, что передавать ход на стадии подготовки нужно по нажатию кнопок, типа - "Я свои корабли расставил, теперь твоя очередь". Само собой, когда стадия подготовки кончится, эти кнопки надо будет убрать

2021-03-29 10:21 UTC, kinekt2000 commented on src/GameWindow.py
> +        self.ui.actionPlayer_2.triggered.connect(self.move_player_2)
Да, вот это дело убирай, у тебя ж виджет, а не главное окно, у него не должно быть никаких меню.

2021-03-29 10:21 UTC, kinekt2000 commented on src/GameWindow.py
> +            raise Exception(f'Unknown type: {self.current_state}')
Круто, но переделывай. Раз уж в PyQt методы camelCase, то и свои делай такими же.

2021-03-29 10:21 UTC, kinekt2000 commented on src/GameWindow.py
> +    def state_machine_next(self, keep_player: bool = False):
Убери "state_machine" из названия метода, назови просто `next(...)` ну или как-то так. Если мы договорились использовать игровой виджет как машину состояний, то нет необходимости указывать это в методе.

2021-03-29 10:21 UTC, kinekt2000 commented on src/GameWindow.py
> +        border-image: url(ship.jpg) 0 0 0 0 stretch stretch;
Фоновое изображение, думаю, пока можно убрать, скорее всего фоновыми изображениями будет управлять Антон.

2021-03-29 10:24 UTC, thehighestmath commented on src/GameWindow.py
> +    def state_machine_next(self, keep_player: bool = False):
Лан, тут соглашусь

2021-03-29 10:24 UTC, thehighestmath commented on src/GameWindow.py
> +        border-image: url(ship.jpg) 0 0 0 0 stretch stretch;
Оки

2021-03-29 10:49 UTC, thehighestmath commented
Хочу approve....

2021-03-29 11:16 UTC, kinekt2000 approved these changes
Кнопки добавь для передачи подготовки другому игроку и сделай это как-нибудь красиво

2021-03-29 11:24 UTC, merged