Controller
thehighestmath/sea_battle pull request #26
Opened 2021-04-16 21:38 UTC by kinekt2000

* Создан класс _Controller_
* Для того, чтобы получить данные от контроллера необходимо подписаться на событие `hit` контроллера.
* После того, как событие обработано, необходимо подтвердить или отменить событие `Controller.accept()` или `Controller.decline()`.
* Слот обработчик события должен принимать первым значением _Controller_, вторым и третьим _int x, y_ соответственно.
* Контроллер интегрирован в _GameArea_
* Для использования контроллера в _GameArea_ необходимо подписаться на событие `GameArea.controller.hit.connect()`

2021-04-16 21:41 UTC, thehighestmath requested changes
А остальное хе
Если работает, то ок

2021-04-16 21:41 UTC, thehighestmath commented on src/Presenter/GameArea.py
> +            if(x >= 0 and x < 10 and y >= 0 and y < 10):
PEP
```suggestion
            if x >= 0 and x < 10 and y >= 0 and y < 10:
```

2021-04-16 21:48 UTC, kinekt2000 commented on src/Presenter/GameArea.py
> +            if(x >= 0 and x < 10 and y >= 0 and y < 10):
Да как ты это находишь, черт

2021-04-16 21:58 UTC, thehighestmath commented on src/Presenter/GameArea.py
> +            if(x >= 0 and x < 10 and y >= 0 and y < 10):
Сам чёрт!

2021-04-16 21:58 UTC, thehighestmath approved these changes
Ну если работает, то мердж

2021-04-17 08:54 UTC, thehighestmath commented on src/Presenter/GameArea.py
> +            if(x >= 0 and x < 10 and y >= 0 and y < 10):
`if 0 <= x < 10 and 0 <= y < 10:`

2021-04-19 15:37 UTC, thehighestmath approved these changes
Завтра буду жалеть, а пока мерджим

2021-04-20 12:43 UTC, thehighestmath approved these changes

2021-04-20 12:43 UTC, merged