ai choose widget
thehighestmath/sea_battle pull request #50
Opened 2021-05-02 10:34 UTC by Akibardin

2021-05-02 10:40 UTC, thehighestmath requested changes
`AIMode` ? А зачем нам `GameLevel` ? Кажется это одно и то же

2021-05-02 10:49 UTC, Akibardin commented
думал, что это для подсчета очков

2021-05-03 13:14 UTC, thehighestmath approved these changes
Вроде бы ок, только мой бот оч сильный. Микрофиксы сделал

2021-05-03 13:14 UTC, thehighestmath commented on src/MainWindow.py
> +        self.gameWindow = GameWindow(player_1, "player_2", GameMode.PVE)
Вроде бы против нас компик играет, а написано что  player_2)

2021-05-12 21:02 UTC, merged